language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Should run gradle clean, gradle build --scan, gradle jar
# See the defaultTasks section in build.gradle
script:
  - ./gradlew -q